<?php
/**
 * @file
 * Defines a special textarea, with drag and drop media driven by Scald and
 * dnd.module.
 */

define('MEE_RENDERED_COPYRIGHT_PATTERN', '/<!--\s*copyright=(\d+)\s*-->(.*)<!--\s*END copyright=\1\s*-->/sU');

/**
 * Implements hook_init().
 */
function mee_init() {
  // @todo add support for SAS and remote this hack
  $GLOBALS['conf']['mee_store_sas'] = FALSE;
}

/**
 * Implements hook_theme().
 */
function mee_theme($existing, $type, $theme, $path) {
  return array(
    'mee_resource_manager' => array(
      'render element' => 'resource_manager',
    ),
  );
}

/**
 * Implements hook_field_info_alter().
 */
function mee_field_info_alter(&$info) {
  $info['text_with_summary']['instance_settings']['mee_enabled'] = 0;
  $info['text_with_summary']['instance_settings']['context'] = '';
}

/**
 * Implements hook_form_alter().
 *
 * Normally this should go in a hook_field_instance_settings_form() if the field
 * belongs to the module. But it is not the case, so we implement in a form
 * alter.
 */
function mee_form_alter(&$form, &$form_state, $form_id) {
  // Verify if we are in the instance settings form.
  if ($form_id !== 'field_ui_field_edit_form' || $form['#field']['type'] !== 'text_with_summary') {
    return;
  }

  // MEE currently supports only node.
  if (!isset($form['#field']['bundles']['node'])) {
    return;
  }

  $settings = $form['#instance']['settings'];

  $context_options = array();
  foreach (scald_contexts() as $name => $context) {
    $context_options[$name] = $context['title'];
  }

  $form['instance']['settings']['mee_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('MEE Enabled'),
    '#description' => t('Enable MEE for this field give you advance resource management. MEE automatically link embedded resource with field so that you have more control over fields, e.g. unpublish linked nodes when a principle resource is unpublished.'),
    '#default_value' => $settings['mee_enabled'],
  );
  $form['instance']['settings']['context'] = array(
    '#type' => 'select',
    '#title' => t('Scald Editor Context'),
    '#description' => t('Choose a Scald Context to use for displaying Scald Atoms included in the textarea during editing.'),
    '#default_value' => $settings['context'],
    '#options' => $context_options,
  );
}

/**
 * Implements hook_field_presave() on behalf of Text module.
 *
 * @todo Find a better approach to avoid possible collision with other "tricky"
 * modules. However we should be safe with Drupal 7 core.
 */
function text_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  // Convert rendered atom back to SAS for on the fly render if required
  if (!variable_get('mee_store_sas', TRUE)) {
    return;
  }

  foreach ($items as $delta => &$item) {
    if (!empty($item['value'])) {
      $item['value'] = scald_rendered_to_sas($item['value']);
    }
  }
}

/**
 * Implements hook_field_insert() on behalf of Text module.
 *
 * @see text_field_presave()
 */
function text_field_insert($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if (!_mee_field_instance_enabled($instance)) {
    return;
  }

  foreach ($items as $delta => $item) {
    list($sids, $copyrights) = _mee_process_item_value($item);

    // Normalize the weight, putting our separator at 0.
    $separator = $item['mee']['resource_manager'][0]['weight'];

    foreach ($sids as $sid) {
      $resource = $item['mee']['resource_manager'][$sid];
      db_insert('mee_resource')
          ->fields(array(
            'content_nid' => $entity->nid,
            'atom_sid' => $sid,
            'field' => $field['field_name'],
            'weight' => $resource['weight'] - $separator,
            'required' => (int) $resource['required'],
            'copyright' => isset($copyrights[$sid]) ? $copyrights[$sid] : '',
          ))
          ->execute();
    }
  }
}

/**
 * Implements hook_field_update() on behalf of Text module.
 *
 * @see text_field_presave()
 */
function text_field_update($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if (!_mee_field_instance_enabled($instance)) {
    return;
  }

  foreach ($items as $delta => $item) {
    list($sids, $copyrights) = _mee_process_item_value($item);

    // In fact, we'll delete all the associations and recreate afterwards
    // the needed one, to be sure that new resources are correctly
    // registered, and that no longer used one are removed.
    db_delete('mee_resource')
        ->condition('content_nid', $entity->nid)
        ->condition('field', $field['field_name'])
        ->execute();

    // Normalize the weight, putting our separator at 0.
    $separator = $item['mee']['resource_manager'][0]['weight'];

    foreach ($sids as $sid) {
      $resource = $item['mee']['resource_manager'][$sid];
      db_insert('mee_resource')
          ->fields(array(
            'content_nid' => $entity->nid,
            'atom_sid' => $sid,
            'field' => $field['field_name'],
            'weight' => $resource['weight'] - $separator,
            'required' => (int) $resource['required'],
            'copyright' => isset($copyrights[$sid]) ? $copyrights[$sid] : '',
          ))
          ->execute();
    }
  }
}

/**
 * Implements hook_field_delete() on behalf of Text module.
 *
 * @see text_field_presave()
 */
function text_field_delete($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if (!_mee_field_instance_enabled($instance)) {
    return;
  }

  foreach ($items as $delta => $item) {
    scald_unregister_atom(scald_search(array('base_id' => $entity->nid . ':' . $delta), FALSE, TRUE));
  }

  // Delete all resource associations for this field
  db_delete('mee_resource')
      ->condition('content_nid', $entity->nid)
      ->condition('field', $field['field_name'])
      ->execute();
}

/**
 * Implements hook_field_widget_form_alter().
 */
function mee_field_widget_form_alter(&$element, &$form_state, $context) {
  // Add our custom form element into MEE enabled textarea only.
  if (empty($context['instance']['settings']['mee_enabled'])) {
    return;
  }

  $element['mee'] = array(
    '#prefix' => '<div class="mee-wrap-editor-library">',
    '#suffix' => '</div>',
    '#attached' => array(
      'css' => array(drupal_get_path('module', 'mee') . '/css/mee.css'),
      'js' => array(drupal_get_path('module', 'mee')  . '/mee.js'),
    ),
    '#weight' => 0.5,
    'resource_manager' => array(
      '#theme' => 'mee_resource_manager',
    ),
  );

  $resource_manager = array();
  if (isset($form_state['values'])) {
    $resource_manager = $form_state['values']['mee'];
  }
  elseif (isset($element['#entity']->nid)) {
    $result = db_select('mee_resource', 'r')
        ->fields('r', array('atom_sid', 'weight', 'required'))
        ->condition('content_nid', $element['#entity']->nid)
        ->condition('field', $context['field']['field_name'])
        ->orderBy('weight')
        ->execute();
    foreach ($result as $r) {
      $resource_manager[$r->atom_sid] = (array) $r;
    }
  }

  foreach ($resource_manager as $sid => $item) {
    $atom = scald_fetch($sid);
    if (!is_object($atom)) {
      continue;
    }
    $title = $atom->title;

    $element['mee']['resource_manager'][$sid] = array(
      'title' => array(
        '#markup' => $title,
      ),
      'required' => array(
        '#type' => 'select',
        '#options' => array(t('Optional'), t('Required')),
        '#default_value' => $item['required'],
      ),
      'weight' => array(
        '#type' => 'weight',
        '#default_value' => $item['weight'],
      ),
      '#weight' => $item['weight'],
    );
  }

  // And now we add the separator
  $element['mee']['resource_manager'][0] = array(
    'title' => array(
      '#markup' => t('< Primary / Secondary >'),
    ),
    'required' => array(
      '#markup' => '-',
    ),
    'weight' => array(
      '#type' => 'weight',
      '#prefix' => '<div class="mee-rm-separator">',
      '#suffix' => '</div>',
    ),
    '#weight' => isset($resource_manager[0]['weight']) ? $resource_manager[0]['weight'] : 0,
  );

  // Force an #id so that we can reference to it later
  $element['#id'] = drupal_html_id('edit-' . $context['field']['field_name']);

  $element += array(
    '#dnd-enabled' => TRUE,
    '#dnd-settings' => array(
      'drop_selector' => '#' . $element['#id'] . ' .drop',
    ),
  );
}

/**
 * Returns HTML for the MEE resource list.
 *
 * @param $variables
 *   An associative array containing:
 *   - resource_manager: A render element representing the MEE resource list.
 */
function theme_mee_resource_manager($variables) {
  $form = $variables['resource_manager'];
  static $count = 0;
  $id = 'mee-resource-manager-' . $count;
  drupal_add_tabledrag($id, 'order', 'sibling', 'mee-rm-weight');

  $count++;
  $header = array(t('Title'), t('Required'), t('Weight'));
  $rows = array();
  foreach (element_children($form) as $key) {
    $form[$key]['weight']['#attributes']['class'] = array('mee-rm-weight');
    $row = array();
    $row[] = drupal_render($form[$key]['title']);
    $row[] = drupal_render($form[$key]['required']);
    $row[] = drupal_render($form[$key]['weight']);
    $rows[] = array('data' => $row, 'class' => array('draggable'));
  }

  $output = theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array(
      'id' => $id,
      'class' => array('mee-resource-manager'),
    ),
    'caption' => t('Resource Manager'),
  ));
  $output .= drupal_render_children($form);

  return $output;
}

/**
 * Tests if MEE is supported and enabled for this field instance.
 */
function _mee_field_instance_enabled($instance) {
  if ($instance['entity_type'] !== 'node') {
    // @todo support entities other than nodes.
    return FALSE;
  }

  // If MEE is not enabled on this field, there is nothing to do.
  if (empty($instance['settings']['mee_enabled'])) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Extracts sids and copyright from $item. Updates $item if necessary.
 */
function _mee_process_item_value(&$item) {
  // $sids contients the list of atom sid actually used in the item.
  $sas = scald_rendered_to_sas($item['value']);
  $scald_included = scald_included($sas);
  $sids = array_unique($scald_included);

  // Parse copyright informations
  $copyrights = mee_extract_copyrights($item['value']);

  // If $item['mee'] does not hold anything, load default data into it.
  if (empty($item['mee']) || !is_array($item['mee']['resource_manager'])) {
    _mee_load_resources($entity, $field, $item);
  }

  // Finally, if there was unknown client-side problem, we might not have new
  // inserted resources. We set default value for them.
  foreach ($sids as $sid) {
    if (!isset($item['mee']['resource_manager'][$sid])) {
      $item['mee']['resource_manager'][$sid] = array('required' => FALSE, 'weight' => 0);
    }
  }

  return array($sids, $copyrights);
}

/**
 * Load used resource in a node into an array.
 *
 * @param $item renderable array to render the field
 */
function _mee_load_resources($node, $field, &$item) {
  $result = db_select('mee_resource', 'r')
      ->fields('r', array('atom_sid', 'weight'))
      ->condition('content_nid', $node->nid)
      ->condition('field', $field['field_name'])
      ->execute();
  $item['mee']['resource_manager'] = array();
  foreach ($result as $r) {
    $item['mee']['resource_manager'][$r->atom_sid] = array('weight' => $r->weight);
  }
  $item['mee']['resource_manager'][0] = array('weight' => 0);
}

/**
 * Extract all copyright informations from a string.
 */
function mee_extract_copyrights($string) {
  $copyrights = array();
  if (preg_match_all(MEE_RENDERED_COPYRIGHT_PATTERN, $string, $matches)) {
    foreach ($matches[1] as $key => $sid) {
      $copyrights[$sid] = $matches[2][$key];
    }
  }
  return $copyrights;
}

