<?php

/**
 * @file
 * Scald Soundcloud Installation
 */



/**
 * Implementation of hook_install().
 */
function scald_soundcloud_install() {
  // @@@TODO: Pre-populate appropriate variables/configuration
  scald_add_type('audio', 'Audio', 'Resource audio');
}



/**
 * Implementation of hook_uninstall().
 */
function scald_soundcloud_uninstall() {
  // @@@TODO: Delete all variables/configs/blocks/etc.
}