<?php

/**
 * @file
 * Scald Images Installation
 */



/**
 * Implements hook_install().
 */
function scald_audio_install() {
  scald_add_type('audio', 'Audio', 'Audio');
}



/**
 * Implements hook_uninstall().
 */
function scald_audio_uninstall() {
}



/**
 * Implements of hook_enable().
 */
function scald_audio_enable() {
}



/**
 * Implements of hook_disable().
 */
function scald_audio_disable() {
}
